
services:
  db:
    image: postgres:17-alpine
    container_name: my-db
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data"
    networks:
      - app-network

  eureka-server-1:
    build: ./eureka
    container_name: eureka-server-1
    ports:
      - "8761:8761"
    environment:
      EUREKA_INSTANCE_HOSTNAME: eureka-server-1
      EUREKA_CLIENT_REGISTER_WITH_EUREKA: "false"
      EUREKA_CLIENT_FETCH_REGISTRY: "false"
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server-2:8762/eureka/
    networks:
      - app-network

  eureka-server-2:
    build: ./eureka
    container_name: eureka-server-2
    ports:
      - "8762:8761"
    environment:
      EUREKA_INSTANCE_HOSTNAME: eureka-server-2
      EUREKA_CLIENT_REGISTER_WITH_EUREKA: "false"
      EUREKA_CLIENT_FETCH_REGISTRY: "false"
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server-1:8761/eureka/
    networks:
      - app-network

  app:
    build: book-service
    container_name: my-app
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/mydb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server-1:8761/eureka/,http://eureka-server-2:8762/eureka/
    depends_on:
      - eureka-server-1
      - eureka-server-2
      - db
    networks:
      - app-network

  notification:
    build: ./notification-service
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server-1:8761/eureka/,http://eureka-server-2:8762/eureka/
    depends_on:
      - eureka-server-1
      - eureka-server-2
    networks:
      - app-network

networks:
  app-network:
    driver: bridge